module.exports = {
    filter: '.',
    indent: '  ',
    dev: true,
    peer: true,
    prod: true,
    resolutions: true,
    overrides: true,
    pnpmOverrides: true,
    workspace: true,
    semverGroups: [],
    semverRange: '^',
    sortAz: ['dependencies', 'devDependencies', 'peerDependencies'],
    sortFirst: [
        'name',
        'version',
        'private',
        'keywords',
        'description',
        'author',
        'license',
        'scripts',
        'publishConfig',
        'repository',
        'homepage',
        'bugs',
        'type',
        'main',
        'dependencies',
        'devDependencies',
        'peerDependencies'
    ],
    source: [],
    versionGroups: []
};
